image: Visual Studio 2015  # образ для сборки

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (запоминаем информацию о процессе в переменной $App)
  - $App = Start-Process -FilePath java -ArgumentList "-jar ./artifacts/app-order.jar" -PassThru

build_script:
  - gradlew test --info
  
on_finish:
  - Stop-Process -Id $App.Id  # оставливаем SUT
